#!/usr/bin/env python
"""
Stellaris Diff Scanner (Optimized with Rename Block Caching)
--------------------------------
Compares two Stellaris game folders and detects changes to modding definitions and script documentation.

Features:
- Game Data: Scans traits, techs, triggers, effects, civics, etc. from common/
- Rename Detection: Uses fuzzy matching (cydifflib/difflib) to find renamed items.
- Logs: Optionally compares triggers.log and effects.log for script documentation diffs.

MIT License
Copyright (c) 2025 FirePrince
"""

import re
import logging
import argparse
from datetime import datetime
from pathlib import Path
import os
from collections import Counter

try:
	# Try using the faster C implementation
	from cydifflib import SequenceMatcher as FastMatcher
	SequenceMatcher = FastMatcher
	print("Using cydifflib for faster diffs")
except ImportError:
	# Fall back to the Python stdlib
	from difflib import SequenceMatcher
	print("cydifflib not available, using standard difflib")

# Default Test Paths (can be overridden by CLI args)
old_version_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\Stellaris3.14")
new_version_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\Stellaris4.3b")
old_log_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\logs\\Stellaris.logs.3.14")
new_log_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\logs\\Stellaris.logs.4.3")
#####
old_version_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\Stellaris4.2")
new_version_folder = Path("d:\\Steam\\steamapps\\common\\Stellaris")
old_log_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\logs\\Stellaris.logs.4.2")
new_log_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\logs\\Stellaris.logs.4.3")
#####

optional_mod_folder = Path("d:\\GOG Games\\Settings\\Stellaris\\Stellaris4.2_fix") # For scan_usage mode

# Configuration - Add/Remove more categories if needed, e.g. # "variables", "menace_perks", "starbase_buildings", "jobs" , "starbase_modules", "inline_scripts"
rename_chk_cats = { "buildings", "triggers", "effects", "traits", "civics", "modifiers", "traditions", "jobs" , "starbase_modules", "inline_scripts" }
scan_events = True
scan_common = True
scan_usage = False # of scripted triggers and effects
do_logs = True
debug = False

# Logging Setup
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

diff_file_name = 'Stellaris_scanned_diff-list.log'
header = f"# This file was generated by Stellaris Diff Scanner on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} (by FirePrince)"
# header += "# https://github.com/F1r3Pr1nc3/Stellaris-Mod-Updater/blob/main/stellaris_diff_scanner.py"

# Regex for Log Parsing
LOG_ENTRY_BLOCK_REGEX = re.compile(
	r'^(\S+)\s+-\s+[^\n]+\n(.*?)(?=\n\S+ - |\Z)',
	re.MULTILINE | re.DOTALL
)
MODIFIER_ENTRY_REGEX = re.compile(r'^-\s*([^,]+?),\s*(.*)', re.MULTILINE)

def parse_args():
	parser = argparse.ArgumentParser(description="Compare two Stellaris directories and list modding diffs")
	parser.add_argument("old", nargs="?", type=Path, help="Path to the old version of Stellaris")
	parser.add_argument("new", nargs="?", type=Path, help="Path to the new version of Stellaris")
	parser.add_argument("--debug", action="store_true", help="Enable debug logging")
	parser.add_argument("--events", action="store_true", help="Enable event ID scanning")
	parser.add_argument("--common", action="store_true", help="Enable common folder name scanning")
	parser.add_argument("--logs", action="store_true", help="Enable triggers.log, effects.log and modifiers.log scanning")
	parser.add_argument("--count_usage", action="store_true", help="Enable usage counting for scripted triggers and effects")
	parser.add_argument("--mod", type=Path, help="Optional mod folder path for optimization")
	return parser.parse_args()

def write_summary(path: Path, title, lines, info):
	if lines:
		with (path / diff_file_name).open('a', encoding='utf-8') as f:
			f.write(f'\n\n= {title} =\n\n')
			f.write('\n'.join(lines))
		logger.info(f"{info} written to: {diff_file_name}")

def extract_keys(folder: Path, compiled_pattern):
	keys = {}
	if not folder.exists():
		return keys

	if compiled_pattern is None:
		for file_path in folder.rglob("*.txt"):
			if file_path.is_file():
				key = file_path.relative_to(folder).with_suffix("").as_posix()
				keys[key] = file_path.name
	else:
		for file_path in folder.iterdir():
			if file_path.is_file() and file_path.suffix == ".txt":
				with file_path.open('r', encoding='utf-8') as f:
					content = f.read()
					matches = compiled_pattern.findall(content)
					for match in matches:
						if match != "inline_script":
							keys[match] = file_path.name
	return keys

def extract_event_ids(folder: Path):
	event_ids = {}
	if not folder.exists():
		return event_ids

	event_block_pattern = re.compile(r'^\w*?event = \{', re.MULTILINE)
	id_pattern = re.compile(r'^\s+id = ([\w.\-]+)', re.MULTILINE)

	for file_path in folder.iterdir():
		if file_path.suffix != ".txt":
			continue
		with file_path.open('r', encoding='utf-8') as f:
			content = f.read()

		for match in event_block_pattern.finditer(content):
			block_start = match.end()
			block_slice = content[block_start:block_start + 300]
			id_match = id_pattern.search(block_slice)
			if id_match:
				event_id = id_match.group(1)
				event_ids[event_id] = file_path.name
	return event_ids

def extract_all_blocks(folder: Path, pattern):
	blocks = {}
	if not folder.exists():
		return blocks

	if pattern is None:
		for file_path in folder.rglob("*.txt"):
			if file_path.is_file():
				with file_path.open('r', encoding='utf-8') as f:
					content = f.read()
				key = file_path.relative_to(folder).with_suffix("").as_posix()
				blocks[key] = (content.strip(), file_path.name)
		return blocks

	is_block = "\n"
	if (pattern.flags & re.MULTILINE) == re.MULTILINE:
		is_block = "\n}\n"

	for file_path in folder.iterdir():
		if not file_path.is_file() or file_path.suffix != ".txt":
			continue

		with file_path.open('r', encoding='utf-8') as f:
			content = f.read()

		for match in pattern.finditer(content):
			key = match.group(1)
			start = match.start()
			end_idx = content.find(is_block, match.end())
			if end_idx == -1:
				end_idx = len(content)
			block_text = content[start:end_idx].strip()
			blocks[key] = (block_text, file_path.name)
	return blocks

def detect_renamed_blocks(old_dict, new_dict, removed_keys, added_keys, threshold) -> list:
	renames = []
	matched_new_keys = {}
	logger.info(f"⇔ Starting renamed block detection: {len(removed_keys)} removed keys, {len(added_keys)} added keys")
	for old_key in removed_keys:
		if old_key not in old_dict:
			continue
		old_body = old_dict[old_key][0]
		best_match = None
		best_ratio = threshold
		for new_key in added_keys:
			if new_key not in new_dict:
				continue
			new_body = new_dict[new_key][0]
			ratio = SequenceMatcher(None, old_body, new_body).ratio()
			if ratio > best_ratio:
				best_match = new_key
				best_ratio = ratio

		if best_match:
			best_ratio = round(best_ratio * 100, 3)
			old_file = old_dict[old_key][1]
			new_file = new_dict[best_match][1]
			old_key_to_remove = matched_new_keys.get(best_match, False)

			if not old_key_to_remove or old_key_to_remove[1] < best_ratio:
				if old_key_to_remove:
					old_key_to_remove = old_key_to_remove[0]
					renames = [r for r in renames if r[0] != old_key_to_remove]
				matched_new_keys[best_match] = (old_key, best_ratio)
				renames.append((old_key, best_match, best_ratio, old_file, new_file))
				logger.info(f"Potentially renamed: {old_key} -> {best_match} ({best_ratio}%)")

	logger.info(f"⇔ Renamed block detection completed: {len(renames)} potentially renamed pairs found")
	return renames

def write_diffs(old_items, new_items, category, old_path, new_path, renamed_pairs=None):
	summary_lines = []
	if renamed_pairs:
		renamed_old_keys = {old for old, _, _, _, _ in renamed_pairs}
		renamed_new_keys = {new for _, new, _, _, _ in renamed_pairs}
		old_items = [i for i in old_items if i not in renamed_old_keys]
		new_items = [i for i in new_items if i not in renamed_new_keys]
		renamed_pairs = [f"{old} ({old_file}) -> {new} ({new_file}) ({ratio}%)" for old, new, ratio, old_file, new_file in renamed_pairs]
		summary_lines.append(f"	Renamed: {len(renamed_pairs)}")

	added = sorted(set(new_items) - set(old_items))
	removed = sorted(set(old_items) - set(new_items))

	summary_lines.append(f"	Added:	{len(added)}")
	summary_lines.append(f"	Removed: {len(removed)}")

	write_summary(old_path, f"{category.upper()}", summary_lines, category)
	write_summary(old_path, f"{category}_renamed.list", renamed_pairs, category)
	write_summary(old_path, f"{category}_diff_added.list", added, category)
	write_summary(old_path, f"{category}_diff_removed.list", removed, category)

	logger.info(f"[{category.upper()}] Added: {len(added)}, Removed: {len(removed)}")
	return added, removed, renamed_pairs if renamed_pairs else []

def get_subfolder_names(folder_path: Path) -> set[str]:
	if not folder_path.is_dir():
		logger.warning(f"The path '{folder_path}' is not a valid directory.")
		return set()
	subfolder_names = set()
	for entry_path in folder_path.iterdir():
		if entry_path.is_dir():
			subfolder_names.add(entry_path.name)
	return subfolder_names

# --- Log Scanning Functions ---

def extract_log_blocks(file_path: Path, regex_pattern) -> dict:
	"""
	Extracts a dictionary of {entry_name: (description_block, filename)} from a log file.
	"""
	if not file_path.exists():
		logger.warning(f"File not found: {file_path}")
		return {}
	with file_path.open('r', encoding='utf-8', errors='replace') as f:
		content = f.read()
	matches = regex_pattern.findall(content)
	# Store as (content, filename) tuple to be compatible with detect_renamed_blocks
	# Include name in content for better rename detection
	return {name: (f"{name} {desc.strip()}", file_path.name) for name, desc in matches}

def compare_logs(old_log_path, new_log_path, old_path: Path, new_path: Path):
	logger.info("Processing LOGS (triggers.log, effects.log, modifiers.log)...")

	# Try to find logs in root or 'logs' subdirectory
	old_logs_dir = old_log_path if (old_log_path / "triggers.log").exists() else old_log_path / "logs"
	new_logs_dir = new_log_path if (new_log_path / "triggers.log").exists() else new_log_path / "logs"

	log_files = {
		"triggers.log": LOG_ENTRY_BLOCK_REGEX,
		"effects.log": LOG_ENTRY_BLOCK_REGEX,
		"modifiers.log": MODIFIER_ENTRY_REGEX
	}

	for log_file, pattern in log_files.items():
		old_file = old_logs_dir / log_file
		new_file = new_logs_dir / log_file

		cat = log_file.split('.')[0] # triggers or effects
		logger.info(f"Scanning {cat}...")

		old_blocks = extract_log_blocks(old_file, pattern)
		new_blocks = extract_log_blocks(new_file, pattern)

		logger.info(f"	Found {len(old_blocks)} items in old {log_file}")
		logger.info(f"	Found {len(new_blocks)} items in new {log_file}")

		old_keys = set(old_blocks.keys())
		new_keys = set(new_blocks.keys())

		removed = old_keys - new_keys
		added = new_keys - old_keys

		# Reuse the generic renamed block detector
		# Filter blocks to only removed/added for performance
		old_blocks_subset = {k: old_blocks[k] for k in removed if k in old_blocks}
		new_blocks_subset = {k: new_blocks[k] for k in added if k in new_blocks}

		renamed = None
		if log_file in rename_chk_cats:
			renamed = detect_renamed_blocks(old_blocks_subset, new_blocks_subset, removed, added, threshold=0.74)

		# Write standard list diffs
		write_diffs(old_keys, new_keys, f"Native_{cat}_log", old_path, new_path, renamed)

def count_global_usages(folder: Path) -> Counter:
	"""
	Scans all .txt files in the folder (recursively), strips comments,
	and counts word occurrences to estimate usage.
	"""
	logger.info(f"Counting usages in {folder}...")
	usage_counter = Counter()
	# Pre-compile regex for performance
	comment_re = re.compile(r'#.*')
	token_re = re.compile(r'\w+')

	for file_path in folder.rglob("*.txt"):
		if not file_path.is_file():
			continue
		try:
			with file_path.open('r', encoding='utf-8', errors='replace') as f:
				content = f.read()
				# Remove comments
				content = comment_re.sub('', content)
				# Find words
				words = token_re.findall(content)
				usage_counter.update(words)
		except Exception as e:
			logger.warning(f"Failed to read {file_path}: {e}")

	return usage_counter

def write_usage_file(items: set, counter: Counter, category: str, path: Path):
	"""
	Writes a list of items with their usage counts to a separate file.
	Excludes the definition itself (count - 1).
	"""
	filename = f"{category}_usage_counts.txt"

	# Calculate counts first
	usage_list = []
	for item in items:
		count = max(0, counter[item] - 1)
		usage_list.append((item, count))

	# Sort by count descending, then by item name ascending
	usage_list.sort(key=lambda x: (-x[1], x[0]))

	lines = [f"{item} ({count})" for item, count in usage_list]

	with (path / filename).open('w', encoding='utf-8') as f:
		f.write(f"# Usage counts for {category}\n")
		f.write('\n'.join(lines))
	logger.info(f"{category} usage counts written to: {filename}")

def optimize_mod_triggers(mod_path: Path, usage_counter: Counter = None):
	"""
	Scans the mod's scripted_triggers and adds 'optimize_memory # Vfix opt'
	to each trigger if not already present AND usage count is > 37.
	"""
	triggers_path = mod_path / "common" / "scripted_triggers"
	if not triggers_path.exists():
		logger.warning(f"Mod scripted_triggers folder not found: {triggers_path}")
		return

	logger.info(f"Optimizing scripted triggers in: {triggers_path}")

	# Regex to find trigger definitions: key = {
	trigger_def_re = re.compile(r'^([\w\d_]+)\s*=\s*\{', re.MULTILINE)
	# Regex to check if optimize_memory follows immediately (allowing comments/newlines)
	# We look for optimize_memory at the start of the string (after the match)
	check_re = re.compile(r'^\s*(?:#.*?\n\s*)*optimize_memory', re.MULTILINE)

	for file_path in triggers_path.rglob("*.txt"):
		if not file_path.is_file():
			continue

		try:
			with file_path.open('r', encoding='utf-8') as f:
				content = f.read()

			new_content = []
			last_pos = 0
			modified = False

			for match in trigger_def_re.finditer(content):
				trigger_name = match.group(1)
				# Append text up to the end of "key = {"
				new_content.append(content[last_pos:match.end()])

				# Check what comes next
				post_match = content[match.end():]

				# Optimization condition: count > 37
				usage_count = usage_counter.get(trigger_name, 0) - 1 if usage_counter else 0

				if usage_count > 37 and not check_re.match(post_match):
					# optimize_memory NOT found "immediately"
					# Insert it with newlines to ensure safety regarding comments
					new_content.append('\n\toptimize_memory # Vfix opt')
					modified = True

				last_pos = match.end()

			if modified:
				new_content.append(content[last_pos:])
				final_text = "".join(new_content)
				# Clean up potentially double newlines if we care, but safety first
				with file_path.open('w', encoding='utf-8') as f:
					f.write(final_text)
				logger.info(f"Optimized: {file_path.name}")

		except Exception as e:
			logger.error(f"Failed to optimize {file_path}: {e}")


def compare_stellaris_data(old_path: Path, new_path: Path, mod_path: Path = None):
	# Initialize diff file
	try:
		(old_path / diff_file_name).unlink(missing_ok=True)
	except Exception:
		pass

	with (old_path / diff_file_name).open('w', encoding='utf-8') as f:
		f.write(header)

	global_usage_counter = None
	if scan_usage:
		global_usage_counter = count_global_usages(new_path)

	category_configs = {
		"traits":			(re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/traits"), 0.62),
		"techs":			(re.compile(r'^(tech_\w+) = \{', re.MULTILINE), Path("common/technology"), 0.62),
		"triggers":			(re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/scripted_triggers"), 0.62),
		"traditions":		(re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/traditions"), 0.62),
		"effects":			(re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/scripted_effects"), 0.62),
		"jobs":				(re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/pop_jobs"), 0.62),
		"buildings":		(re.compile(r'^((?:building|holding)_\w+) = \{', re.MULTILINE), Path("common/buildings"), 0.62),
		"menace_perks":		(re.compile(r'^(menp_\w+) = \{', re.MULTILINE), Path("common/menace_perks"), 0.62),
		"starbase_buildings": (re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/starbase_buildings"), 0.62),
		"starbase_modules": (re.compile(r'^(\w+) = \{', re.MULTILINE), Path("common/starbase_modules"), 0.62),
		"districts":		(re.compile(r'^(district_\w+) = \{', re.MULTILINE), Path("common/districts"), 0.62),
		"civics":			(re.compile(r'^((?:civic|origin)_\w+) = \{', re.MULTILINE), Path("common/governments/civics"), 0.62),
		"governments":		(re.compile(r'^(gov_\w+)\s*=\s*\{', re.MULTILINE), Path("common/governments"), 0.62),
		"script_values":	(re.compile(r'^(\w+)\s*=', re.MULTILINE), Path("common/script_values"), 0.62),
		"variables":		(re.compile(r'^@(\w+)\s*=', re.MULTILINE), Path("common/scripted_variables"), 0.62),
		"defines":			(re.compile(r'^\t+([A-Z0-9_]+)\s*=', re.MULTILINE), Path("common/defines"), 0.62),
		"colony_types":		(re.compile(r'^(col_\w+)\s*=\s*\{', re.MULTILINE), Path("common/colony_types"), 0.62),
		"inline_scripts": (None, Path("common/inline_scripts"), 0.74),
	}

	for cat, (pattern, subpath, threshold) in category_configs.items():
		logger.info(f"Processing category: {cat.upper()}")
		old_dir = old_path / subpath
		new_dir = new_path / subpath

		old_keys = extract_keys(old_dir, pattern)
		new_keys = extract_keys(new_dir, pattern)

		old_items = set(old_keys.keys())
		new_items = set(new_keys.keys())

		renamed = None
		if cat in rename_chk_cats:
			old_blocks_all = extract_all_blocks(old_dir, pattern)
			new_blocks_all = extract_all_blocks(new_dir, pattern)

			removed = old_items - new_items
			added = new_items - old_items

			old_blocks = {k: old_blocks_all[k] for k in removed if k in old_blocks_all}
			new_blocks = {k: new_blocks_all[k] for k in added if k in new_blocks_all}

			renamed = detect_renamed_blocks(old_blocks, new_blocks, removed, added, threshold)

		write_diffs(old_items, new_items, cat, old_path, new_path, renamed)

		if scan_usage and global_usage_counter and cat in ["triggers", "effects"]:
			write_usage_file(new_items, global_usage_counter, cat, old_path)

			# If we are processing triggers and usage scan is active, check for mod optimization
			if cat == "triggers" and mod_path:
				optimize_mod_triggers(mod_path, global_usage_counter)

	# Modifiers
	modifier_paths = [
		Path("common/opinion_modifiers"),
		Path("common/planet_modifiers"),
		Path("common/scripted_modifiers"),
		Path("common/static_modifiers"),
	]
	pattern = re.compile(r'^(\w+) = \{', re.MULTILINE)
	old_mod_dirs = [old_path / p for p in modifier_paths]
	new_mod_dirs = [new_path / p for p in modifier_paths]

	old_keys = {}
	new_keys = {}
	for d in old_mod_dirs:
		old_keys.update(extract_keys(d, pattern))
	for d in new_mod_dirs:
		new_keys.update(extract_keys(d, pattern))

	old_items = set(old_keys.keys())
	new_items = set(new_keys.keys())

	renamed = None
	if "modifiers" in rename_chk_cats:
		old_blocks_all = {}
		new_blocks_all = {}
		for d in old_mod_dirs:
			old_blocks_all.update(extract_all_blocks(d, pattern))
		for d in new_mod_dirs:
			new_blocks_all.update(extract_all_blocks(d, pattern))

		removed = old_items - new_items
		added = new_items - old_items

		old_blocks = {k: old_blocks_all[k] for k in removed if k in old_blocks_all}
		new_blocks = {k: new_blocks_all[k] for k in added if k in new_blocks_all}

		renamed = detect_renamed_blocks(old_blocks, new_blocks, removed, added, threshold=0.62)

	write_diffs(old_items, new_items, "modifiers", old_path, new_path, renamed)

	if scan_events:
		logger.info("Processing category: EVENTS...")
		old_ids = set(extract_event_ids(old_path / "events").keys())
		new_ids = set(extract_event_ids(new_path / "events").keys())
		write_diffs(old_ids, new_ids, "events", old_path, new_path)

	if scan_common:
		logger.info("Processing COMMON subdirectory structure...")
		old_folders = get_subfolder_names(old_path / "common")
		new_folders = get_subfolder_names(new_path / "common")
		write_diffs(old_folders, new_folders, "common", old_path, new_path)

	if do_logs:
		compare_logs(old_log_folder, new_log_folder, old_path, new_path)

if __name__ == "__main__":
	args = parse_args()

	if args.old and args.new:
		old_path = args.old
		new_path = args.new
	else:
		print("No arguments provided, using default test paths...")
		old_path = old_version_folder
		new_path = new_version_folder

	if args.debug:
		debug = args.debug
		logger.setLevel(logging.DEBUG)
	if args.events:
		scan_events = args.events
	if args.common:
		scan_common = args.common
	if args.count_usage:
		scan_usage = args.count_usage

	mod_path = args.mod if args.mod else optional_mod_folder
	compare_stellaris_data(old_path, new_path, mod_path)
